name: Laravel Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql

    - name: Instalar Dependências do Composer
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./backend

    - name: Preparar ambiente (Cópia do .env)
      run: cp .env.example .env
      working-directory: ./backend

    - name: Gerar Application Key
      run: php artisan key:generate
      working-directory: ./backend

    # Opcional para o futuro: Executar testes automatizados
    # - name: Executar Testes
    #   run: php artisan test
    #   working-directory: ./backend
